FORMAT: 1A
HOST: http://www.google.com

# Tournament Manager API
Manage tournaments easily as a team, ref, or tournament director.

# Group Tournaments
Tournaments related resources of the **Tournament Manager API**

## Tournaments Collection [/tournaments]
### List all Tournaments [GET]
+ Response 200 (application/json)

        [{
          "id": "200000000000000000000000", 
          "name": "Northeast Regionals",
          "date": "11/13/2013",
          "director": "Rob Clifford"
        }, {
          "id": "400000000000000000000000", 
          "name": "Snowbelt Championship",
          "date": "12/01/2012",
          "director": "Jeff Sherman"
        }]

### Create a Tournament [POST]
+ Request (application/json)

        { 
          "name": "World Cup 7",
          "date": "04/05/2013",
          "director": "Logan Anbinder"
        }

+ Response 201 (application/json)

        { 
          "id": "600000000000000000000000",
          "name": "World Cup 7",
          "date": "04/05/2013",
          "director": "Logan Anbinder"
        }

## Tournament [/tournaments/{id}]
A single Tournament object with its top level data

+ Parameters
    + id (required, string, `45af236dc25e2f5029addf12`) ... Hexadecimal string `id` of the Tournament to perform action with. Has example value.

### Retrieve a Tournament [GET]

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { 
              "id": "900000000000000000000000",
              "name": "World Cup 8",
              "date": "04/05/2014",
              "director": "Josh Kramer"
            }


### Remove a Tournament [DELETE]
+ Response 204

## Tournament Details [/tournaments/{id}/details]
A single Tournament object with its top and second level data (Games and Teams)

### Retrieve a Tournament [GET]

+ Parameters
    + id (required, string, `45af236dc25e2f5029addf12`) ... Hexadecimal string `id` of the Tournament to perform action with. Has example value.

+ Response 200 (application/json)

    + Body
    
            { 
                "id": "900000000000000000000000",
                "name": "World Cup 8",
                "date": "04/05/2014",
                "director": "Josh Kramer",
                "teams": [
                    {
                        "id": "900000000000000000000001",
                        "name": "RIT Dark Marks"
                    },
                    {
                        "id": "900000000000000000000002",
                        "name": "Boston University"
                    },
                    {
                        "id": "900000000000000000000003",
                        "name": "U of R Thestrals"
                    },
                    {
                        "id": "900000000000000000000013",
                        "name": "NY Badassalisks"
                    }
                ],
                "games": [
                    {
                        "id": "900000000000000000000004",
                        "pitch": "1",
                        "startTime": "2014-04-09T11:20+05:00",
                        "headReferee": {
                            "id": "400000000000000000000001",
                            "name": "Jeff Sherman"
                        },
                         "snitch": {
                            "id": "400000000000000000000011",
                            "name": "Max Desmond"
                        },
                        "teams": [
                            {
                                "id": "900000000000000000000003",
                                "name": "U of R Thestrals"
                            },
                            {
                                "id": "900000000000000000000002",
                                "name": "Boston University"
                            }
                        ]
                    },
                    {
                        "id": "900000000000000000000006",
                        "pitch": "2",
                        "startTime": "2014-04-09T09:20+05:00",
                        "endTime": "2014-04-09T09:43+05:00",
                        "headReferee": {
                            "id": "400000000000000000000002",
                            "name": "Samy Mousa"
                        },
                        "snitch": {
                            "id": "400000000000000000000011",
                            "name": "Max Desmond"
                        },
                        "teams": [
                            {
                                "id": "900000000000000000000001",
                                "name": "RIT Dark Marks"
                            },
                            {
                                "id": "900000000000000000000002",
                                "name": "Boston University"
                            }
                        ],
                        "assistantReferees": [
                            {
                            "id": "400000000000000000000003",
                            "name": "Josh Kramer"
                        },
                        {
                            "id": "400000000000000000000004",
                            "name": "Snow Woodcock"
                        },
                        {
                            "id": "400000000000000000000005",
                            "name": "Kyle Leslie"
                        },
                        {
                            "id": "400000000000000000000006",
                            "name": "John Goinn"
                        }
                        ]
                    }
                ]
            }
            
# Group Games
Game related resources of the **Tournament Manager API**

## Games Collection [/tournaments/{id}/games]
+ Parameters
    + id (required, string, `45af236dc25e2f5029addf13`) ... Hexadecimal string `id` of the Tournament to perform action with. Has example value.

### List all Games [GET]
+ Response 200 (application/json)
    
        [
            {
                "id": "900000000000000000000004",
                "pitch": "1",
                "startTime": "2014-04-09T11:20+05:00",
                "headReferee": {
                    "id": "400000000000000000000001",
                    "name": "Jeff Sherman"
                },
                 "snitch": {
                    "id": "400000000000000000000011",
                    "name": "Max Desmond"
                },
                "teams": [
                    {
                        "id": "900000000000000000000003",
                        "name": "U of R Thestrals"
                    },
                    {
                        "id": "900000000000000000000002",
                        "name": "Boston University"
                    }
                ]
            },
            {
                "id": "900000000000000000000006",
                "pitch": "2",
                "startTime": "2014-04-09T09:20+05:00",
                "endTime": "2014-04-09T09:43+05:00",
                "headReferee": {
                    "id": "400000000000000000000002",
                    "name": "Samy Mousa"
                },
                "snitch": {
                    "id": "400000000000000000000011",
                    "name": "Max Desmond"
                },
                "teams": [
                    {
                        "id": "900000000000000000000001",
                        "name": "RIT Dark Marks"
                    },
                    {
                        "id": "900000000000000000000002",
                        "name": "Boston University"
                    }
                ],
                "assistantReferees": [
                    {
                    "id": "400000000000000000000003",
                    "name": "Josh Kramer"
                },
                {
                    "id": "400000000000000000000004",
                    "name": "Snow Woodcock"
                },
                {
                    "id": "400000000000000000000005",
                    "name": "Kyle Leslie"
                },
                {
                    "id": "400000000000000000000006",
                    "name": "John Goinn"
                }
                ]
            }
        ]

### Create a Game [POST]

+ Request (application/json)
    
        {
            "pitch": "1",
            "startTime": "2014-04-09T11:20+05:00",
            "headReferee": {
                "id": "400000000000000000000001",
                "name": "Jeff Sherman"
            },
             "snitch": {
                "id": "400000000000000000000011",
                "name": "Max Desmond"
            },
            "teams": [
                {
                    "id": "900000000000000000000003",
                    "name": "U of R Thestrals"
                },
                {
                    "id": "900000000000000000000002",
                    "name": "Boston University"
                }
            ]
        }

+ Response 200 (application/json)

        {
            "id": "900000000000000000000004",
            "pitch": "1",
            "startTime": "2014-04-09T11:20+05:00",
            "headReferee": {
                "id": "400000000000000000000001",
                "name": "Jeff Sherman"
            },
             "snitch": {
                "id": "400000000000000000000011",
                "name": "Max Desmond"
            },
            "teams": [
                {
                    "id": "900000000000000000000003",
                    "name": "U of R Thestrals"
                },
                {
                    "id": "900000000000000000000002",
                    "name": "Boston University"
                }
            ]
        }

## Game [/tournaments/{tournamentid}/games/{gameid}]
+ Parameters
    + tournamentid (required, string, `45af236dc25e2f5029addf13`) ... Hexadecimal string `id` of the Tournament to perform action with. Has example value.
    + gameid (required, string, `45af236dc25e2f5029add313`) ... Hexadecimal string `id` of the Game to perform action with. Has example value.

### Retrieve a Game [GET]
+ Response 200 (application/json)
    
        {
            "id": "900000000000000000000004",
            "pitch": "1",
            "startTime": "2014-04-09T11:20+05:00",
            "headReferee": {
                "id": "400000000000000000000001",
                "name": "Jeff Sherman"
            },
             "snitch": {
                "id": "400000000000000000000011",
                "name": "Max Desmond"
            },
            "teams": [
                {
                    "id": "900000000000000000000003",
                    "name": "U of R Thestrals"
                },
                {
                    "id": "900000000000000000000002",
                    "name": "Boston University"
                }
            ]
        }

### Remove a Came [DELETE]
+ Response 204

## Teams Collection [/teams]

### List all Teams [GET]
+ Response 200 (application/json)
    
        [
            {
                "id": "900000000000000000000001",
                "name": "RIT Dark Marks"
            },
            {
                "id": "900000000000000000000002",
                "name": "Boston University"
            },
            {
                "id": "900000000000000000000003",
                "name": "U of R Thestrals"
            },
            {
                "id": "900000000000000000000013",
                "name": "NY Badassalisks"
            },
            {
                "id": "900000000000000000000023",
                "name": "Tufflepuffs"
            }
        ]

### Create a Team [POST]

+ Request (application/json)
    
        {
            "name": "RIT Dark Marks"
        }

+ Response 200 (application/json)

        {
            "id": "900000000000000000000001",
            "name": "RIT Dark Marks"
        }


## Team [/teams/{id}]
+ Parameters
    + id (required, string, `45af236dc25e2f5029addf13`) ... Hexadecimal string `id` of the Team to perform action with. Has example value.

### Retrieve a Team [GET]
+ Response 200 (application/json)
    
        {
            "id": "900000000000000000000002",
            "name": "Boston University"
        }


### Remove a Team [DELETE]
+ Response 204


