FORMAT: 1A
HOST: http://www.google.com

# Tournament Manager API
Manage tournaments easily as a team, ref, or tournament director.

# Group Tournaments
Tournaments related resources of the **Tournament Manager API**

## Tournaments Collection [/tournaments]
### List all Tournaments [GET]
+ Response 200 (application/json)

        [{
          "id": "200000000000000000000000", 
          "name": "Northeast Regionals",
          "date": "11/13/2013",
          "director": "Rob Clifford"
        }, {
          "id": "400000000000000000000000", 
          "name": "Snowbelt Championship",
          "date": "12/01/2012",
          "director": "Jeff Sherman"
        }]

### Create a Tournament [POST]
+ Request (application/json)

        { 
          "name": "World Cup 7",
          "date": "04/05/2013",
          "director": "Logan Anbinder"
        }

+ Response 201 (application/json)

        { 
          "id": "600000000000000000000000",
          "name": "World Cup 7",
          "date": "04/05/2013",
          "director": "Logan Anbinder"
        }

## Tournament [/tournaments/{id}]
A single Tournament object with its top level data

+ Parameters
    + id (required, string, `45af236dc25e2f5029addf12`) ... Hexadecimal string `id` of the Tournament to perform action with. Has example value.

### Retrieve a Tournament [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { 
              "id": "900000000000000000000000",
              "name": "World Cup 8",
              "date": "04/05/2014",
              "director": "Josh Kramer"
            }


### Remove a Note [DELETE]
+ Response 204
