FORMAT: 1A
HOST: http://iqatournaments.com

# iqatournaments
Manage tournaments easily as a team, ref, or tournament director.

# Group Tournaments
Tournaments related resources of the **iqatournaments** API

## Tournaments Collection [/tournaments]

### List all Tournaments [GET]
+ Response 200 (application/json)

        [{
          "id": "23456",
          "alias": "northeastregionals2013",
          "name": "Northeast Regionals",
          "location": "Rochester, NY",
          "date": "2013-11-13",
          "director": {
            "id": "52d582dde6c8a500004f275b",
            "name": "Rob Clifford"
          }
        }, {
          "id": "34534",
          "alias": "snowbeltchampionship2012",
          "name": "Snowbelt Championship",
          "location": "Rochester, NY",
          "date": "2012-12-01",
          "director": {
            "id": "52d582dde6c8a500004f275a",
            "name": "Jeff Sherman"
          }
        },
        {
          "id": "35235",
          "alias": "worldcup7",
          "name": "World Cup 7",
          "location": "Myrtle Beach, SC",
          "date": "2013-04-05",
          "director": {
            "id": "52d582dde6c8a500004f275d",
            "name": "Logan Anbinder"
          }
        }]

### Create a Tournament [POST]
The 'alias' must be unique, can only consist of a-z, 0-9, and '-'. Ids containing uppercase values will be converted to lowercase before being stored.
+ Request (application/json)

        {
          "alias": "WorldCup7"
          "name": "World Cup 7",
          "location": "Myrtle Beach, SC",
          "date": "2013-04-05",
          "director": {
            "id": "52d582dde6c8a500004f275d",
            "name": "Logan Anbinder"
          }
        }

+ Response 201 (application/json)

        {
          "id": "34636",
          "alias": "worldcup7",
          "name": "World Cup 7",
          "location": "Myrtle Beach, SC",
          "date": "2013-04-05",
          "director": {
            "id": "52d582dde6c8a500004f275d",
            "name": "Logan Anbinder"
          }
        }

## Tournament [/tournaments/{alias}]
A single Tournament object with its top level data.

+ Parameters
    + alias (required, string) ... The id or alias of the requested tournament, case insensitive.


### Retrieve a Tournament [GET]
A single Tournament object with its top and second level data (Games and Teams)

+ Parameters
    + alias (required, string) ... The id of the requested tournament, case insensitive.

+ Response 200 (application/json)

    + Body

            {
                "id": "23509",
                "alias": "worldcup7",
                "name": "World Cup 7",
                "location": "Myrtle Beach, SC",
                "date": "2014-04-05",
                "director": {
                  "id": "52d582dde6c8a500004f275b",
                  "name": "Rob Clifford"
                },
                "teams": [
                    {
                        "id": "90000",
                        "name": "RIT Dark Marks"
                    },
                    {
                        "id": "90002",
                        "name": "Boston University"
                    },
                    {
                        "id": "90003",
                        "name": "U of R Thestrals"
                    },
                    {
                        "id": "90013",
                        "name": "NY Badassalisks"
                    }
                ],
                "games": [
                    {
                        "id": "90004",
                        "pitch": "1",
                        "startTime": "2014-04-09T11:20+05:00",
                        "headReferee": {
                            "id": "40001",
                            "name": "Jeff Sherman"
                        },
                         "snitch": {
                            "id": "40011",
                            "name": "Max Desmond"
                        },
                        "team1": {
                            "id": "90003",
                            "name": "U of R Thestrals"
                        },
                        "team2": {
                            "id": "90002",
                            "name": "Boston University"
                        }
                    },
                    {
                        "id": "90006",
                        "pitch": "2",
                        "startTime": "2014-04-09T09:20+05:00",
                        "endTime": "2014-04-09T09:43+05:00",
                        "gameTime": "17:32",
                        "headReferee": {
                            "id": "40002",
                            "name": "Samy Mousa"
                        },
                        "snitch": {
                            "id": "400011",
                            "name": "Max Desmond"
                        },
                        "team1": {
                            "id": "90001",
                            "name": "RIT Dark Marks",
                            "score": 100,
                            "snatch": true
                        },
                        "team2": {
                            "id": "90002",
                            "name": "Boston University",
                            "score": 90,
                            "snatch": false
                        },
                        "assistantReferees": [
                            {
                            "id": "40003",
                            "name": "Josh Kramer"
                        },
                        {
                            "id": "40004",
                            "name": "Snow Woodcock"
                        },
                        {
                            "id": "40005",
                            "name": "Kyle Leslie"
                        },
                        {
                            "id": "40006",
                            "name": "John Goinn"
                        }
                        ]
                    }
                ]
            }

### Remove a Tournament [DELETE]
+ Response 204

### Modify a Tournament [PUT]
Modify a single tournament. Only can modify the top level fields using this endpoint.
To modify the teams and games use the /tournaments/{id}/teams and /tournaments/{id}/games endpoints.

+ Parameters
    + alias (required, string) ... The id of the requested tournament before the
request, case insensitive. If id is included in the PATCH data it will
change for future requests.

+ Request

        {
            "alias": "world-cup-7",
            "location": "Los Angeles, CA",
            "date": "2015-04-05"
        }

+ Response 200 (application/json)

    + Body

            {
                "id": "23534",
                "alias": "world-cup-7",
                "name": "World Cup 7",
                "location": "Los Angeles, CA",
                "date": "2015-04-05",
                "director": {
                  "id": "52d582dde6c8a500004f275b",
                  "name": "Rob Clifford"
                },
                "teams": [
                    {
                        "id": "90001",
                        "name": "RIT Dark Marks"
                    },
                    {
                        "id": "90002",
                        "name": "Boston University"
                    },
                    {
                        "id": "90003",
                        "name": "U of R Thestrals"
                    },
                    {
                        "id": "90013",
                        "name": "NY Badassalisks"
                    }
                ],
                "games": [
                    {
                        "id": "90004",
                        "pitch": "1",
                        "startTime": "2014-04-09T11:20+05:00",
                        "headReferee": {
                            "id": "40001",
                            "name": "Jeff Sherman"
                        },
                         "snitch": {
                            "id": "40011",
                            "name": "Max Desmond"
                        },
                        "teams": [
                            {
                                "id": "90003",
                                "name": "U of R Thestrals"
                            },
                            {
                                "id": "90002",
                                "name": "Boston University"
                            }
                        ]
                    },
                    {
                        "id": "90006",
                        "pitch": "2",
                        "startTime": "2014-04-09T09:20+05:00",
                        "endTime": "2014-04-09T09:43+05:00",
                        "gameTime": "17:32",
                        "headReferee": {
                            "id": "40002",
                            "name": "Samy Mousa"
                        },
                        "snitch": {
                            "id": "40011",
                            "name": "Max Desmond"
                        },
                        "teams": [
                            {
                                "id": "90001",
                                "name": "RIT Dark Marks",
                                "score": 100,
                                "snatch": true
                            },
                            {
                                "id": "90002",
                                "name": "Boston University",
                                "score": 90,
                                "snatch": false
                            }
                        ],
                        "assistantReferees": [
                            {
                            "id": "40003",
                            "name": "Josh Kramer"
                        },
                        {
                            "id": "40004",
                            "name": "Snow Woodcock"
                        },
                        {
                            "id": "40005",
                            "name": "Kyle Leslie"
                        },
                        {
                            "id": "40006",
                            "name": "John Goinn"
                        }
                        ]
                    }
                ]
            }


# Group Games
Game related resources of the **IQA Tournaments API**

## Games Collection [/tournaments/{alias}/games]
+ Parameters
    + alias (required, string) ... The id of the requested tournament before the
request, case insensitive.

### List all Games [GET]
+ Response 200 (application/json)

        [
            {
                "id": "90004",
                "pitch": "1",
                "startTime": "2014-04-09T11:20+05:00",
                "headReferee": {
                    "id": "40001",
                    "name": "Jeff Sherman"
                },
                 "snitch": {
                    "id": "40011",
                    "name": "Max Desmond"
                },
                "team1": {
                    "id": "90003",
                    "alias": "urthestrals",
                    "name": "U of R Thestrals"
                },
                "team2": {
                    "id": "90002",
                    "alias": "bostonuniversity",
                    "name": "Boston University"
                }
            },
            {
                "id": "90006",
                "pitch": "2",
                "startTime": "2014-04-09T09:20+05:00",
                "endTime": "2014-04-09T09:43+05:00",
                "gameTime": "17:32",
                "headReferee": {
                    "id": "40002",
                    "name": "Samy Mousa"
                },
                "snitch": {
                    "id": "40011",
                    "name": "Max Desmond"
                },
                "team1": {
                    "id": "90001",
                    "alias": "ritdarkmarks",
                    "name": "RIT Dark Marks"
                    "score": 100
                    "snatch": true
                },
                "team2": {
                    "id": "90002",
                    "alias": "bostonuniversity",
                    "name": "Boston University",
                    "score": 90,
                    "snatch": false
                },
                "assistantReferees": [
                    {
                    "id": "40003",
                    "name": "Josh Kramer"
                    },
                    {
                        "id": "40004",
                        "name": "Snow Woodcock"
                    },
                    {
                        "id": "40005",
                        "name": "Kyle Leslie"
                    },
                    {
                        "id": "40006",
                        "name": "John Goinn"
                    }
                ]
            }
        ]

### Create a Game [POST]

+ Request (application/json)

        {
            "pitch": "1",
            "startTime": "2014-04-09T11:20+05:00",
            "headReferee": {
                "id": "40001",
                "name": "Jeff Sherman"
            },
             "snitch": {
                "id": "40011",
                "name": "Max Desmond"
            },
            "teams": [
                {
                    "id": "90003",
                    "alias": "urthestrals",
                    "name": "U of R Thestrals"
                },
                {
                    "id": "90002",
                    "alias": "bostonuniversity",
                    "name": "Boston University"
                }
            ]
        }

+ Response 200 (application/json)

        {
            "id": "90004",
            "pitch": "1",
            "startTime": "2014-04-09T11:20+05:00",
            "headReferee": {
                "id": "40001",
                "name": "Jeff Sherman"
            },
             "snitch": {
                "id": "40011",
                "name": "Max Desmond"
            },
            "teams": [
                {
                    "id": "90003",
                    "alias": "urthestrals",
                    "name": "U of R Thestrals"
                },
                {
                    "id": "90002",
                    "alias": "bostonuniversity",
                    "name": "Boston University"
                }
            ]
        }

## Game [/tournaments/{tournamentalias}/games/{gameid}]
+ Parameters
    + tournamentalias (required, string) ... The alias of the requested tournament, case insensitive.
    + gameid (required, string) ... The id of the requested game

### Retrieve a Game [GET]
+ Response 200 (application/json)

        {
            "id": "90004",
            "pitch": "1",
            "startTime": "2014-04-09T11:20+05:00",
            "headReferee": {
                "id": "40001",
                "name": "Jeff Sherman"
            },
             "snitch": {
                "id": "40011",
                "name": "Max Desmond"
            },
            "teams": [
                {
                    "id": "90003",
                    "alias": "urthestrals",
                    "name": "U of R Thestrals"
                },
                {
                    "id": "90002",
                    "alias": "bostonuniversity",
                    "name": "Boston University"
                }
            ]
        }

### Remove a Came [DELETE]
+ Response 204

### Modify a Game [PATCH]
Modify a single game. Only can modify the top level fields using this endpoint.
To modify assistant referees use /tournaments/{tournamentalias}/games/{gameid}/assistantreferees.

+ Parameters
    + tournamentalias (required, string) ... The alias of the requested tournament, case insensitive.
    + gameid (required, string) ... The id of the requested game (can't be changed).

+ Request

        {
            "pitch": "5",
            "startTime": "2014-04-09T12:00+05:00",
            "headReferee": {
                "id": "40002"
            },
            "team1": {
                "id": "40018"
            }
        }

+ Response 200 (application/json)

        {
            "id": "90004",
            "pitch": "5",
            "startTime": "2014-04-09T12:00+05:00",
            "headReferee": {
                "id": "40002",
                "name": "Samy Mousa"
            },
             "snitch": {
                "id": "40011",
                "name": "Max Desmond"
            },
            "team1": {
                "id": "90018",
                "alias": "syracuse",
                "name": "Syracuse University"
            },
            "team2": {
                "id": "90002",
                "alias": "bostonuniversity",
                "name": "Boston University"
            }
        }


## Game [/tournaments/{tournamentalias}/games/{gameid}/assistantreferees]
+ Parameters
    + tournamentalias (required, string) ... The alias of the requested tournament, case insensitive.
    + gameid (required, string) ... The id of the requested game

### Add a referee [POST]

+ Request

        {
            "id": "40011"
        }

+ Response 200

        [
            {
                "id": "40003",
                "name": "Josh Kramer"
            },
            {
                "id": "40004",
                "name": "Snow Woodcock"
            },
            {
                "id": "40005",
                "name": "Kyle Leslie"
            },
            {
                "id": "40006",
                "name": "John Goinn"
            },
            {
                "id": "40011",
                "name": "Max Desmond"
            }
        ]

### Delete a referee [DELETE]

+ Request

        {
            "id": "40011"
        }

+ Response 200

        [
            {
                "id": "40003",
                "name": "Josh Kramer"
            },
            {
                "id": "40004",
                "name": "Snow Woodcock"
            },
            {
                "id": "40005",
                "name": "Kyle Leslie"
            },
            {
                "id": "40006",
                "name": "John Goinn"
            }
        ]

# Group Teams

## Teams Collection [/teams]
Will be extended in the future to contain a roster and a captain. This will
allow the API to return schedule conflicts for people possibly refereeing.

### List all Teams [GET]
+ Response 200 (application/json)

        [
            {
                "id": "90001",
                "alias": "ritdarkmarks",
                "name": "RIT Dark Marks"
            },
            {
                "id": "90002",
                "alias": "bostonuniversity",
                "name": "Boston University"
            },
            {
                "id": "90003",
                "alias": "urthestrals",
                "name": "U of R Thestrals"
            },
            {
                "id": "90013",
                "alias": "badassalisks",
                "name": "NY Badassalisks"
            },
            {
                "id": "90023",
                "alias": "tufflepuffs",
                "name": "Tufflepuffs"
            }
        ]

### Create a Team [POST]

+ Request (application/json)

        {
            "name": "RIT Dark Marks",
            "alias": "ritdarkmarks"
        }

+ Response 200 (application/json)

        {
            "id": "90001",
            "alias": "ritdarkmarks",
            "name": "RIT Dark Marks"
        }


## Team [/teams/{alias}]
+ Parameters
    + alias (required, string) ... `alias` of the Team to perform action with.

### Retrieve a Team [GET]
+ Response 200 (application/json)

        {
            "id": "90002",
            "alias": "bostonuniversity",
            "name": "Boston University"
        }

### Remove a Team [DELETE]
+ Response 204

# Group Person

## Person [/person]

### Create a Person [POST]
+ Request

        {
            "name": "Adam Smith"
        }

+ Response 200 (application/json)

        {
            "id": "90023",
            "name": "Adam Smith"
        }

## Person [/person/{id}]
+ Parameters
    + id (required, string) ... `id` of the Person to perform action with.

### Retrieve a Person [GET]
+ Response 200 (application/json)

        {
            "id": "90011",
            "name": "Max Desmond"
        }

### Remove a Person [DELETE]
+ Response 204


